Read Saint Kitts and Nevis' BUR1 from pdf
JGuetschow/UNFCCC_non-AnnexI_data pull request #102
Opened 2024-08-01 13:55 UTC by crdanielbusch

## Description

Work in progress

## Checklist

Please confirm that this pull request has done the following:

- [ ] Tests added
- [ ] Documentation added (where applicable)
- [ ] Changelog item added to `changelog/`

2024-08-12 13:52 UTC, JGuetschow commented
I think we need the agriculture trend table from pages 131/132, so we can obtain all PRIMAP-hist sectors for all gases through downscaling.

2024-08-27 08:53 UTC, crdanielbusch commented
> I think we need the agriculture trend table from pages 131/132, so we can obtain all PRIMAP-hist sectors for all gases through downscaling.

The data from the table on pages 131/132 is already read in with the overview table on pages 111/112/113.

We now have the sectors 3 / 3.A / 3.B / 3.C and 3.D  for 2008 to 2018 (with 3.D being NE for all years) and KYOTOGHG (AR6GWP100). Do you mean downscaling entities for the years 2008-2018? For example, create values for N2O and CH4 for 3.A for all the years based on the values of 2018?

2024-08-28 12:01 UTC, crdanielbusch commented
@JGuetschow I updated the downscaling for most primap sectors. We now have the values by entity for 2008-2018  for the categories:

1, 1.A, 1.B, 3, 3.A, 3.B, 3.C, 3.D, 4

Still missing are the values for the categories 2, 2.A, 2.B, 2.C, 2.D, 2.E, 2.F, 2.G, 2.H. They are all zero and the downscaling currently does not work for that.

Also, we don't have the trend for 1.C, as there are no values for KYOTOGHG.

2024-09-04 07:45 UTC, JGuetschow requested changes

2024-09-04 09:32 UTC, crdanielbusch commented on src/unfccc_ghg_data/unfccc_reader/Saint_Kitts_and_Nevis/config_kna_bur1.py
> +            "2.  Oil and Natural Gas and other…": "1.B.2",
The categories `1.B.2` and `1.B.3` are in the table on page 125. Wouldn't it be better to drop `M.1.B.23` and work with the values directly assigned to the categories?

2024-09-04 09:33 UTC, crdanielbusch commented on src/unfccc_ghg_data/unfccc_reader/Saint_Kitts_and_Nevis/config_kna_bur1.py
> +            "D.  Agricultural Soils": "3.C.4",  # TODO confirm! 3c4 and 3c5
Ok noted

2024-09-04 09:46 UTC, crdanielbusch commented on src/unfccc_ghg_data/unfccc_reader/Saint_Kitts_and_Nevis/config_kna_bur1.py
> +        "M.3.D.AG": {"sources": ["3.D.2"]},
Haven't seen this and already changed it in the code

2024-09-04 09:47 UTC, crdanielbusch commented on src/unfccc_ghg_data/unfccc_reader/Saint_Kitts_and_Nevis/config_kna_bur1.py
> +        "M.LULUCF": {"sources": ["3.B", "M.3.D.LU"]},
Done

2024-09-04 09:47 UTC, crdanielbusch commented on src/unfccc_ghg_data/unfccc_reader/Saint_Kitts_and_Nevis/config_kna_bur1.py
> +            "I.  Other carbon-containing": "3.D.2",  # TODO confirm! ?
Done

2024-09-09 07:06 UTC, crdanielbusch commented on src/unfccc_ghg_data/unfccc_reader/Saint_Kitts_and_Nevis/config_kna_bur1.py
> +            "NO,NE": "NO",
Ok I can do that

2024-09-09 07:18 UTC, JGuetschow commented on src/unfccc_ghg_data/unfccc_reader/Saint_Kitts_and_Nevis/config_kna_bur1.py
> +            "2.  Oil and Natural Gas and other…": "1.B.2",
If they are present already, that's of course better than downscaling. Though I see only aggregate Kyoto GHG in the table, so some downscaling is still needed.

2024-09-09 09:58 UTC, crdanielbusch commented on src/unfccc_ghg_data/unfccc_reader/Saint_Kitts_and_Nevis/config_kna_bur1.py
> +            "NO,NE": "NO",
Had a closer look at this one. I don't think it's necessary to open an issue. I replaced the `,` with `.` in the data column. The values `NO,NE` then turned into `NO.NE` which can recognised as string code anymore.

2024-09-09 10:04 UTC, JGuetschow approved these changes

2024-09-09 11:00 UTC, merged