Mongolia bur2 remaining tables
JGuetschow/UNFCCC_non-AnnexI_data pull request #89
Opened 2024-05-23 13:40 UTC by crdanielbusch

Work in progress.

- [x] Add `notebook` to dependencies
- [x] Add `ipympl` to dependencies (needed to show interactive plots in jupyter notebooks)
- [x] Read more important tables: 32, 43-44, 74,  103, 114-115, 119, 125-126, 151, 157, 161-162
- [x] Deal with less important tables (skip for now but mention that they exist and what they contain in the code)
67, 78, 91, 105/6, 110/111

2024-05-27 09:13 UTC, JGuetschow commented
The `notebook`, `ipympl`, and 'ipywidgets`  dependencies should be in the dev dependencies not in the main dependencies as the notebooks are only used during development.

2024-07-08 12:04 UTC, JGuetschow requested changes
Looks good, but will not work with current code because of sector aggregation specifications. 
If downscaling is necessary but not yet implemented we can take a look together,

2024-07-08 12:04 UTC, JGuetschow commented on src/unfccc_ghg_data/unfccc_reader/Mongolia/read_MNG_BUR2_from_pdf.py
>          processing_info_country=country_processing_step1,
Are all sectors and gases covered for all years, or do you se downscaling or do we have gaps? If there are gaps in subsectors / gases and no downscaling yet, we could take a look together.

2024-07-08 19:23 UTC, crdanielbusch commented on src/unfccc_ghg_data/unfccc_reader/Mongolia/config_mng_bur2.py
> +        "M.AG": {"sources": ["3.A.1", "3.A.2", "M.AG.ELV"], "name": "Agriculture"},
Is 3.A not the same as 3.A.1 and 3.A.2 in this case?

2024-07-08 19:41 UTC, JGuetschow commented on src/unfccc_ghg_data/unfccc_reader/Mongolia/config_mng_bur2.py
> +        "M.AG": {"sources": ["3.A.1", "3.A.2", "M.AG.ELV"], "name": "Agriculture"},
It's the same in terms of building M.AG but we need 3.A as an independent category in PRIMAP-hist

2024-07-10 10:25 UTC, crdanielbusch commented on src/unfccc_ghg_data/unfccc_reader/Mongolia/config_mng_bur2.py
> +        "M.3.C.AG": {
They are present in the overview tables. So that's fine?

2024-07-10 10:28 UTC, crdanielbusch commented on src/unfccc_ghg_data/unfccc_reader/Mongolia/config_mng_bur2.py
> +        "M.AG": {"sources": ["3.A.1", "3.A.2", "M.AG.ELV"], "name": "Agriculture"},
3.A is in the overview tables. Do I still not to aggregate 3.A then?

2024-07-29 14:05 UTC, JGuetschow approved these changes

2024-07-30 08:46 UTC, merged